language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COVERAGE="--coverage build/logs/clover.xml --coverage-src src -d extension=xdebug.so"
  - COVERAGE=""

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

  exclude:
    - php: 5.5
      env: COVERAGE=""

    - php: 5.6
      env: COVERAGE=""

    - php: 7.0
      env: COVERAGE="--coverage build/logs/clover.xml --coverage-src src -d extension=xdebug.so"

    - php: hhvm
      env: COVERAGE="--coverage build/logs/clover.xml --coverage-src src -d extension=xdebug.so"

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction --prefer-source --dev
  - vendor/bin/parallel-lint --exclude vendor --exclude tests .
  - vendor/bin/phpcs src --standard=vendor/dotblue/codesniffer-ruleset/DotBlue/ruleset.xml -s
  - mkdir -p build/logs

script:
  - vendor/bin/tester tests -p php $COVERAGE
  - src/babylon tests/data/php7 output
  - vendor/bin/parallel-lint output

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

after_script:
  - vendor/bin/test-reporter
